@host = http://localhost:3000/api/users


### Sync users
POST https://userslistapp-api-rest.onrender.com/api/users/sync

### Get users from DB
GET https://userslistapp-api-rest.onrender.com/api/users/users

### Create user
PUT {{host}}/users
Content-Type: application/json

{
    "name":"Magnus",
    "username": "Carlsen",
    "email":"carlsenchess@gmail.com", 
    "external_id": "11", 
    "address":{"street":"133 nw avenue"}
}