@host = http://localhost:3000/api/users

### Sync users
POST {{host}}/sync

### Get users from DB
GET {{host}}/users

### Create user
PUT {{host}}/users
Content-Type: application/json

{
    "name":"Magnus",
    "username": "Carlsen",
    "email":"carlsenchess@gmail.com", 
    "external_id": "11", 
    "address":{"street":"133 nw avenue"}
}